Bootstrap:docker
From:ubuntu:bionic-20180526

%environment
    export LC_ALL=C
    #export WINEARCH="win32"  # Set wine to handle 32 bit
    export WINEPREFIX=/wineprefix64  # Get a clean prefix
    export WINEDISTRO=devel
    export WINEPATH="C:\pwiz"
    export WINEDEBUG=-all,err+all  # Hide all wine related output

    # Making so user who logs into the image can use wine
    mkdir -p "/tmp/wineprefix64_$USER"
    random_name=$(date +%s | sha256sum | base64 | head -c 32)
    mkdir -p "/tmp/wineprefix64_$USER/wineprefix64_$random_name"  # Create folder, so you are owner
    link_wine.sh $random_name # This script will link all files in $WINEPREFIX and input them in /var/local/shared_wine/wineprefix64
    export WINEPREFIX="/tmp/wineprefix64_$USER/wineprefix64_$random_name"  # Change prefix, so wine will know you are the owner

    mkdir -p /tmp/runtime-$USER
    export XDG_RUNTIME_DIR=/tmp/runtime-$USER
    export XDG_CONFIG_HOME=/tmp/runtime-$USER

%labels
   AUTHOR lukas.kall@scilifelab.se and timothy.bergstrom@gmail.com

%files
   pwiz.tar.bz2 /pwiz.tar.bz2
   link_wine.sh /usr/local/bin/link_wine.sh

%post
    export WINEPREFIX=/wineprefix64  # Get a clean prefix
    export WINEDISTRO=devel
    export WINEPATH="C:\pwiz"

    echo "INSTALLING UTILS"
    dpkg --add-architecture i386  # Add 32 bit compability
    apt-get update  # Update to install needed utils
    apt-get install -y software-properties-common winbind cabextract p7zip unzip wget zenity xvfb # Utils
    apt-get install -y nano
    rm -rf /var/lib/apt/lists/*

    echo "INSTALLING WINE"
    wget -nc https://dl.winehq.org/wine-builds/winehq.key  # Get key for newest version
    apt-key add winehq.key  # Add the key
    apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'  # Main repo for ubuntu 18.04 LTS
    apt-get update  # Update once again to be able to install wine
    apt-get install -y --install-recommends winehq-$WINEDISTRO wine-$WINEDISTRO wine-$WINEDISTRO-i386 wine-$WINEDISTRO-amd64
    wineboot -u  # Update the prefix
    apt-get -y clean

    echo "INSTALLING PROTEOWIZARD 32 BIT (FULL VENDOR CAPABILITIES)"
    mkdir -p $WINEPREFIX/drive_c/pwiz
    tar xjvf /pwiz.tar.bz2 -C $WINEPREFIX/drive_c/pwiz
    rm /pwiz.tar.bz2

    echo "INSTALLING WINETRICKS"
    wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
    chmod +x winetricks
    cp winetricks /usr/bin/winetricks

    echo "INSTALLING .NET and VC"
    DEBIAN_FRONTEND=noninteractive winetricks -q dotnet472 dotnet40
    wineserver -w
    winetricks -q win7
    xvfb-run winetricks -q vcrun2008 vcrun2017 corefonts
    wineserver -w

%runscript
    echo "Test"
